#!/bin/bash

cmd=$1
bashSource="$(dirname "$(readlink "$(cd "$(dirname "$BASH_SOURCE")" && pwd)/scratch")")"

if [ -f ~/.scratchrc ]
then
  source ~/.scratchrc
fi

if [ -z ${cmd+x} ]
then
  cmd=help
fi

if [ -z ${scratchpadReposDir+x} ]
then
  scratchpadReposDir=$HOME/scratchpad
fi

if [ -z ${scratchpadFilename+x} ]
then
  scratchpadFilename=scratch.md
fi

function getRootCommit {
  if [[ `git rev-list --parents HEAD | tail -1` ]] &>/dev/null
  then
    repo=`git rev-list --parents HEAD | tail -1`
  fi
}

function init {
  if [ -d .git ]
  then
    if [ ! -f .git/hooks/post-checkout ]
    then
      echo "#!/bin/bash" > .git/hooks/post-checkout
      chmod u+x .git/hooks/post-checkout
    fi
    if grep --quiet scratchpad .git/hooks/post-checkout
    then
      echo Scratchpad exists in git hook
    else
      cat "$bashSource/hook" >> .git/hooks/post-checkout
    fi
    getRootCommit
    if [ -z ${repo+x} ]
    then
      echo No root commit
      exit 1
    else
      mkdir -p $scratchpadReposDir/$repo
      touch $scratchpadReposDir/$repo/$scratchpadFilename
      echo "Initialized scratchpad at '$scratchpadReposDir/$repo/$scratchpadFilename'"
    fi
  else
    echo Not a git repository
    exit 1
  fi
}

function prune {
  getRootCommit
}

function save {
  # should have a quiet option for running in hook
  getRootCommit
  currentBranch=$1
  if [ -f $scratchpadReposDir/$repo/$scratchpadFilename ]
  then
    cat $scratchpadReposDir/$repo/$scratchpadFilename > $scratchpadReposDir/$repo/$currentBranch
  else
    echo Missing scratchpad file, try running 'scratch init'
    exit 1
  fi
}

function checkout {
  getRootCommit
  if [ $3 == 1 ] && [ $1 != $2 ] && [ ! -z ${repo+x} ]
  then
    save $1
    if [ -f $scratchpadReposDir/$repo/$2 ]
    then
      cat $scratchpadReposDir/$repo/$2 > $scratchpadReposDir/$repo/$scratchpadFilename
    else
      echo '' > $scratchpadReposDir/$repo/$scratchpadFilename
    fi
    prune
  fi
}

if [[ $cmd == "init" ]]
then
  init
elif [[ $cmd == "checkout" ]]
then
  checkout $2 $3 $4
elif [[ $cmd == "prune" ]]
then
  prune
elif [[ $cmd == "save" ]]
then
  save ${2:-$(git rev-parse HEAD)}
else
  echo Try scratch init
fi
